trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Docker image names
  frontendImageName: adder-frontend
  backendImageName: adder-backend
  mongodbImageName: 'mongodb/mongodb-community-server'
  subscriptionId: 'c061fdd1-bba3-4c63-b32d-6595004a4b00'
  tenantId: '61c44f51-4973-4caf-a8de-cbde54d78efa'
  clientId: 'e12b5802-7b09-428c-900a-7fb5990597c8'
  clientSecret: 'u2W8Q~m47HjHcvCYuf-Iyh3F22HJz8jxWIoi1azb'

  # ACR details
  acrName: adderAcr
  acrLoginServer: adderacr.azurecr.io
  acrUsername: $(az acr credential show --name adderacr --query "username" --output tsv)
  acrPassword: $(az acr credential show --name adderacr --query "passwords[0].value" --output tsv)

stages:
- stage: Build
  jobs:
  - job: BuildAndPushImages
    displayName: Build and Push Docker Images
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - task: AzureCLI@2
      displayName: Azure CLI Login
      inputs:
        azureSubscription: 'deployment-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az login --service-principal -u $(clientId) -p $(clientSecret) --tenant $(tenantId)
          az account set --subscription $(subscriptionId)

    - script: docker build -t $(acrLoginServer)/$(frontendImageName):$(Build.BuildId) frontend
      displayName: Build Frontend Docker Image

    - script: docker build -t $(acrLoginServer)/$(backendImageName):$(Build.BuildId) backend
      displayName: Build Backend Docker Image

    - script: docker pull mongodb/mongodb-community-server
    - script: docker tag $(mongodbImageName) $(acrLoginServer)/samples/$(mongodbImageName)
      displayName: Build MongoDB Docker Image

    - script: docker login $(acrLoginServer) -u $(clientId) -p $(clientSecret)
      displayName: Login to ACR

    - script: docker push $(acrLoginServer)/$(frontendImageName):$(Build.BuildId)
      displayName: Push Frontend Docker Image

    - script: docker push $(acrLoginServer)/$(backendImageName):$(Build.BuildId)
      displayName: Push Backend Docker Image

    - script: docker push $(acrLoginServer)/$(mongodbImageName):$(mongodbImageName)
      displayName: Push MongoDB Docker Image        

- stage: Deploy
  jobs:
  - job: DeployToAzure
    displayName: Deploy to Azure
    steps:
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'deployment-sc'
          appName: 'adder_webapp'
          containers: $(acrLoginServer)/$(frontendImageName):$(Build.BuildId), $(acrLoginServer)/$(backendImageName):$(Build.BuildId), $(acrLoginServer)/$(mongodbImageName)
          multicontainerConfigFile: '**/docker-compose.yml'
          containerCommand: 'up --build'