trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: adder

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build and Publish artifact
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'install and build frontend'

    - task: ArchiveFiles@2
      displayName: 'Archive Files frontend'
      inputs:        
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/frontend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'drop-frontend'
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
      displayName: 'Publish npm artifact frontend'
        
- stage: Deploy
  displayName: Deploy
  condition: succeeded()
  dependsOn: Build
  jobs:
  - deployment: DeployToAzureAppService
    displayName: Deploy to AppService
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              displayName: 'Frontend Deployment to AppService'
              inputs:
                azureSubscription: 'deployment-sc'
                appType: 'webAppLinux'
                appName: 'adder-webapp'
                package: '$(Pipeline.Workspace)/drop-frontend/$(Build.BuildId).zip'
                runtimeStack: 'NODE|20-lts'
                appSettings: '-WEBSITE_RUN_FROM_PACKAGE 0'
