trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  environmentName: 'dev'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build and Publish Artifact
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '20.x'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'
    
    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:        
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/frontend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/drop/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
      displayName: 'Publish Build Artifact'

- stage: Deploy
  displayName: Deploy
  condition: succeeded()
  dependsOn: Build
  jobs:
  - deployment: DeployToAzureAppService
    displayName: Deploy to AppService
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop

            - task: AzureWebApp@1
              displayName: 'Azure Web App Deployment'
              inputs:
                azureSubscription: 'deployment-sc'
                appType: 'webAppLinux'
                appName: 'adder-webapp'
                package: '$(Pipeline.Workspace)/drop/drop/$(Build.BuildId).zip'
                runtimeStack: 'NODE|20-lts'
                startUpCommand: 'npm run dev'