trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Docker image names
  frontendImageName: adder-frontend
  backendImageName: adder-backend
  mongodbImageName: 'mongodb/mongodb-community-server'
  subscriptionId: 'c061fdd1-bba3-4c63-b32d-6595004a4b00'
  tenantId: '61c44f51-4973-4caf-a8de-cbde54d78efa'
  clientId: 'e12b5802-7b09-428c-900a-7fb5990597c8'
  clientSecret: 'u2W8Q~m47HjHcvCYuf-Iyh3F22HJz8jxWIoi1azb'

  # ACR details
  acrName: adderacr
  acrLoginServer: adderacr.azurecr.io
  acrUsername: $(az acr credential show --name adderacr --query "username" --output tsv)
  acrPassword: $(az acr credential show --name adderacr --query "passwords[0].value" --output tsv)

stages:
- stage: Build
  jobs:
  - job: BuildAndPushImages
    displayName: Build and Push Docker Images
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: acr-sc

    - task: DockerCompose@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'deployment-sc'
        projectName: 'adder'
        azureContainerRegistry: '{"loginServer":"adderacr.azurecr.io", "id" : "/subscriptions/c061fdd1-bba3-4c63-b32d-6595004a4b00/resourceGroups/adder-main-rg/providers/Microsoft.ContainerRegistry/registries/adderacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeLatestTag: true
