trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  # Docker image names
  environmentName: 'dev'
  subscriptionId: 'c061fdd1-bba3-4c63-b32d-6595004a4b00'
  tenantId: '61c44f51-4973-4caf-a8de-cbde54d78efa'
  clientId: 'e12b5802-7b09-428c-900a-7fb5990597c8'
  clientSecret: 'u2W8Q~m47HjHcvCYuf-Iyh3F22HJz8jxWIoi1azb'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build and Publish Artifact
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
      displayName: 'npm install'
    
    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:        
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
      displayName: 'Publish npm artifact'

- stage: Deploy
  displayName: Deploy
  condition: succeeded()
  dependsOn: Build
  jobs:
  - deployment: DeployToAzureAppService
    displayName: Deploy to AppService
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              displayName: 'Azure Web App Deployment'
              inputs:
                azureSubscription: deployment-sc
                appType: webAppLinux
                appName: adder-webapp
                package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                startUpCommand: 'npm run dev'
