trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  environmentName: 'dev'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build and Publish Artifact
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '20.x'
        checkLatest: true
      displayName: 'Install Node.js'
    - script: |
        cd frontend
        npm i vite
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
      displayName: 'Publish Build Artifact'

- stage: Deploy
  displayName: Deploy
  condition: succeeded()
  dependsOn: Build
  jobs:
  - deployment: DeployToAzureAppService
    displayName: Deploy to AppService
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'deployment-sc'
                appType: 'webAppLinux'
                appName: 'adder-webapp'
                package: '$(System.DefaultWorkingDirectory)/**/*.zip'
                runtimeStack: 'NODE|18-lts'
                startUpCommand: 'npm run dev'