version: '3'
services:
  backend:
    build: ./backend
    environment:
      - CONN_STR=mongodb://user:pass@mongodb:27017/Adder
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')", "--username=user", "--password=pass", "--authenticationDatabase=Adder"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  mongodb-data:
    driver: local
