services:
  backend:
    build: ./backend
    environment:
      - CONN_STR=mongodb+srv://aabdelwa1:fmnVV4MzJdkQSB8I@cluster0.cadpj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend

    ports:
      - "5173:5173"
    depends_on:
      - backend